version: '3'

services:
  ctop-frontend:
    image: smartcityresearch/ctop-frontend:latest
    container_name: ctop-frontend
    restart: always
    ports:
      - 80:80
    environment:
      - BACKEND_API_URL=http://192.168.0.117:8000
    networks:
      - ctop-network
    depends_on:
      - ctop-backend

  ctop-backend:
    image: smartcityresearch/ctop-backend:latest
    container_name: ctop-backend
    restart: on-failure:10
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://root:toor@postgres:5432/ctOP
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_MINUTES=10080  # 60 * 24 * 7 for 7 days
      - ALGORITHM=HS256
      - JWT_SECRET_KEY=scrc
      - JWT_REFRESH_SECRET_KEY=iiith1234
      - OM2M_URL=http://mobius-app:7579/Mobius
      - OM2M_USERNAME=admin
      - OM2M_PASSWORD=admin
      - MOBIUS_XM2MRI=12345
      - WORKERS=4
    networks:
      - ctop-network
    depends_on:
      - postgres
      - mobius-app

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=ctOP
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - ctop-network

  mobius-db:
    image: mysql:8.0
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_ROOT_PASSWORD=dksdlfduq2
        - MYSQL_DATABASE=mobiusdb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - ./mobiusdb.sql:/docker-entrypoint-initdb.d/mobiusdb.sql
        - mobiusdb-data:/var/lib/mysql 
    restart: always
    healthcheck:
        test: ["CMD", "mysqladmin", "--password=dksdlfduq2", "ping"]
        interval: 20s
        timeout: 20s
        retries: 10
    networks:
      - ctop-network
      
      
  mobius-app:
    image: smartcityresearch/ctop-mobius:latest
    ports:
        - "8200:7579"
    environment:
        - DB_HOST=mobius-db
        - MQTT_BROKER=localhost
    depends_on:
        mobius-db:
            condition: service_healthy
    restart: always
    networks:
      - ctop-network

networks:
  ctop-network:

volumes:
  postgresql-data:
  mobiusdb-data: